/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AgentRouteRouteImport } from "./routes/agent/route";
import { Route as AuthRouteRouteImport } from "./routes/auth/route";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AgentIndexRouteImport } from "./routes/agent/index";
import { Route as AgentThreadIdRouteImport } from "./routes/agent/$threadId";
import { Route as AgentNewRouteImport } from "./routes/agent/new";
import { Route as AuthIndexRouteImport } from "./routes/auth/index";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password";
import { Route as AuthResumePasswordRouteImport } from "./routes/auth/resume-password";
import { Route as AuthVerify2faRouteImport } from "./routes/auth/verify-2fa";
import { Route as AuthVerify2faBackupRouteImport } from "./routes/auth/verify-2fa-backup";
import { Route as BuilderResumeIdRouteRouteImport } from "./routes/builder/$resumeId/route";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as DashboardAccountRouteImport } from "./routes/dashboard/account";
import { Route as BuilderResumeIdIndexRouteImport } from "./routes/builder/$resumeId/index";
import { Route as DashboardAdminFeedbackRouteImport } from "./routes/dashboard/admin/feedback";
import { Route as DashboardAdminPaymentsRouteImport } from "./routes/dashboard/admin/payments";
import { Route as DashboardAdminUsersRouteImport } from "./routes/dashboard/admin/users";
import { Route as DashboardResumesIndexRouteImport } from "./routes/dashboard/resumes/index";
import { Route as DashboardSettingsIntegrationsRouteRouteImport } from "./routes/dashboard/settings/integrations/route";
import { Route as DashboardSettingsPreferencesRouteImport } from "./routes/dashboard/settings/preferences";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AgentRouteRoute = AgentRouteRouteImport.update({
  id: "/agent",
  path: "/agent",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AgentRouteRoute,
} as any);
const AgentThreadIdRoute = AgentThreadIdRouteImport.update({
  id: "/$threadId",
  path: "/$threadId",
  getParentRoute: () => AgentRouteRoute,
} as any);
const AgentNewRoute = AgentNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AgentRouteRoute,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResumePasswordRoute = AuthResumePasswordRouteImport.update({
  id: "/resume-password",
  path: "/resume-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthVerify2faRoute = AuthVerify2faRouteImport.update({
  id: "/verify-2fa",
  path: "/verify-2fa",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthVerify2faBackupRoute = AuthVerify2faBackupRouteImport.update({
  id: "/verify-2fa-backup",
  path: "/verify-2fa-backup",
  getParentRoute: () => AuthRouteRoute,
} as any);
const BuilderResumeIdRouteRoute = BuilderResumeIdRouteRouteImport.update({
  id: "/builder/$resumeId",
  path: "/builder/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const BuilderResumeIdIndexRoute = BuilderResumeIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BuilderResumeIdRouteRoute,
} as any);
const DashboardAdminFeedbackRoute = DashboardAdminFeedbackRouteImport.update({
  id: "/admin/feedback",
  path: "/admin/feedback",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: "/admin/payments",
  path: "/admin/payments",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: "/admin/users",
  path: "/admin/users",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardResumesIndexRoute = DashboardResumesIndexRouteImport.update({
  id: "/resumes/",
  path: "/resumes/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSettingsIntegrationsRouteRoute =
  DashboardSettingsIntegrationsRouteRouteImport.update({
    id: "/settings/integrations",
    path: "/settings/integrations",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsPreferencesRoute =
  DashboardSettingsPreferencesRouteImport.update({
    id: "/settings/preferences",
    path: "/settings/preferences",
    getParentRoute: () => DashboardRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/agent": typeof AgentRouteRouteWithChildren;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/agent/$threadId": typeof AgentThreadIdRoute;
  "/agent/new": typeof AgentNewRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/dashboard/account": typeof DashboardAccountRoute;
  "/agent/": typeof AgentIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRouteRoute;
  "/dashboard/admin/feedback": typeof DashboardAdminFeedbackRoute;
  "/dashboard/admin/payments": typeof DashboardAdminPaymentsRoute;
  "/dashboard/admin/users": typeof DashboardAdminUsersRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/agent/$threadId": typeof AgentThreadIdRoute;
  "/agent/new": typeof AgentNewRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/dashboard/account": typeof DashboardAccountRoute;
  "/agent": typeof AgentIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRouteRoute;
  "/dashboard/admin/feedback": typeof DashboardAdminFeedbackRoute;
  "/dashboard/admin/payments": typeof DashboardAdminPaymentsRoute;
  "/dashboard/admin/users": typeof DashboardAdminUsersRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/builder/$resumeId": typeof BuilderResumeIdIndexRoute;
  "/dashboard/resumes": typeof DashboardResumesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/agent": typeof AgentRouteRouteWithChildren;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/agent/$threadId": typeof AgentThreadIdRoute;
  "/agent/new": typeof AgentNewRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/dashboard/account": typeof DashboardAccountRoute;
  "/agent/": typeof AgentIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRouteRoute;
  "/dashboard/admin/feedback": typeof DashboardAdminFeedbackRoute;
  "/dashboard/admin/payments": typeof DashboardAdminPaymentsRoute;
  "/dashboard/admin/users": typeof DashboardAdminUsersRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agent"
    | "/auth"
    | "/dashboard"
    | "/builder/$resumeId"
    | "/agent/$threadId"
    | "/agent/new"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/dashboard/account"
    | "/agent/"
    | "/auth/"
    | "/dashboard/"
    | "/dashboard/settings/integrations"
    | "/dashboard/admin/feedback"
    | "/dashboard/admin/payments"
    | "/dashboard/admin/users"
    | "/dashboard/settings/preferences"
    | "/builder/$resumeId/"
    | "/dashboard/resumes/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agent/$threadId"
    | "/agent/new"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/dashboard/account"
    | "/agent"
    | "/auth"
    | "/dashboard"
    | "/dashboard/settings/integrations"
    | "/dashboard/admin/feedback"
    | "/dashboard/admin/payments"
    | "/dashboard/admin/users"
    | "/dashboard/settings/preferences"
    | "/builder/$resumeId"
    | "/dashboard/resumes";
  id:
    | "__root__"
    | "/"
    | "/agent"
    | "/auth"
    | "/dashboard"
    | "/builder/$resumeId"
    | "/agent/$threadId"
    | "/agent/new"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/dashboard/account"
    | "/agent/"
    | "/auth/"
    | "/dashboard/"
    | "/dashboard/settings/integrations"
    | "/dashboard/admin/feedback"
    | "/dashboard/admin/payments"
    | "/dashboard/admin/users"
    | "/dashboard/settings/preferences"
    | "/builder/$resumeId/"
    | "/dashboard/resumes/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AgentRouteRoute: typeof AgentRouteRouteWithChildren;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  BuilderResumeIdRouteRoute: typeof BuilderResumeIdRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agent": {
      id: "/agent";
      path: "/agent";
      fullPath: "/agent";
      preLoaderRoute: typeof AgentRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agent/": {
      id: "/agent/";
      path: "/";
      fullPath: "/agent/";
      preLoaderRoute: typeof AgentIndexRouteImport;
      parentRoute: typeof AgentRouteRoute;
    };
    "/agent/$threadId": {
      id: "/agent/$threadId";
      path: "/$threadId";
      fullPath: "/agent/$threadId";
      preLoaderRoute: typeof AgentThreadIdRouteImport;
      parentRoute: typeof AgentRouteRoute;
    };
    "/agent/new": {
      id: "/agent/new";
      path: "/new";
      fullPath: "/agent/new";
      preLoaderRoute: typeof AgentNewRouteImport;
      parentRoute: typeof AgentRouteRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/register": {
      id: "/auth/register";
      path: "/register";
      fullPath: "/auth/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/resume-password": {
      id: "/auth/resume-password";
      path: "/resume-password";
      fullPath: "/auth/resume-password";
      preLoaderRoute: typeof AuthResumePasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/verify-2fa": {
      id: "/auth/verify-2fa";
      path: "/verify-2fa";
      fullPath: "/auth/verify-2fa";
      preLoaderRoute: typeof AuthVerify2faRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/verify-2fa-backup": {
      id: "/auth/verify-2fa-backup";
      path: "/verify-2fa-backup";
      fullPath: "/auth/verify-2fa-backup";
      preLoaderRoute: typeof AuthVerify2faBackupRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/builder/$resumeId": {
      id: "/builder/$resumeId";
      path: "/builder/$resumeId";
      fullPath: "/builder/$resumeId";
      preLoaderRoute: typeof BuilderResumeIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/account": {
      id: "/dashboard/account";
      path: "/account";
      fullPath: "/dashboard/account";
      preLoaderRoute: typeof DashboardAccountRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/builder/$resumeId/": {
      id: "/builder/$resumeId/";
      path: "/";
      fullPath: "/builder/$resumeId/";
      preLoaderRoute: typeof BuilderResumeIdIndexRouteImport;
      parentRoute: typeof BuilderResumeIdRouteRoute;
    };
    "/dashboard/admin/feedback": {
      id: "/dashboard/admin/feedback";
      path: "/admin/feedback";
      fullPath: "/dashboard/admin/feedback";
      preLoaderRoute: typeof DashboardAdminFeedbackRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/admin/payments": {
      id: "/dashboard/admin/payments";
      path: "/admin/payments";
      fullPath: "/dashboard/admin/payments";
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/admin/users": {
      id: "/dashboard/admin/users";
      path: "/admin/users";
      fullPath: "/dashboard/admin/users";
      preLoaderRoute: typeof DashboardAdminUsersRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/resumes/": {
      id: "/dashboard/resumes/";
      path: "/resumes";
      fullPath: "/dashboard/resumes/";
      preLoaderRoute: typeof DashboardResumesIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/integrations": {
      id: "/dashboard/settings/integrations";
      path: "/settings/integrations";
      fullPath: "/dashboard/settings/integrations";
      preLoaderRoute: typeof DashboardSettingsIntegrationsRouteRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/preferences": {
      id: "/dashboard/settings/preferences";
      path: "/settings/preferences";
      fullPath: "/dashboard/settings/preferences";
      preLoaderRoute: typeof DashboardSettingsPreferencesRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
  }
}

interface AgentRouteRouteChildren {
  AgentThreadIdRoute: typeof AgentThreadIdRoute;
  AgentNewRoute: typeof AgentNewRoute;
  AgentIndexRoute: typeof AgentIndexRoute;
}

const AgentRouteRouteChildren: AgentRouteRouteChildren = {
  AgentThreadIdRoute: AgentThreadIdRoute,
  AgentNewRoute: AgentNewRoute,
  AgentIndexRoute: AgentIndexRoute,
};

const AgentRouteRouteWithChildren = AgentRouteRoute._addFileChildren(
  AgentRouteRouteChildren,
);

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthResumePasswordRoute: typeof AuthResumePasswordRoute;
  AuthVerify2faRoute: typeof AuthVerify2faRoute;
  AuthVerify2faBackupRoute: typeof AuthVerify2faBackupRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResumePasswordRoute: AuthResumePasswordRoute,
  AuthVerify2faRoute: AuthVerify2faRoute,
  AuthVerify2faBackupRoute: AuthVerify2faBackupRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardSettingsIntegrationsRouteRoute: typeof DashboardSettingsIntegrationsRouteRoute;
  DashboardAdminFeedbackRoute: typeof DashboardAdminFeedbackRoute;
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute;
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute;
  DashboardSettingsPreferencesRoute: typeof DashboardSettingsPreferencesRoute;
  DashboardResumesIndexRoute: typeof DashboardResumesIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsIntegrationsRouteRoute:
    DashboardSettingsIntegrationsRouteRoute,
  DashboardAdminFeedbackRoute: DashboardAdminFeedbackRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardSettingsPreferencesRoute: DashboardSettingsPreferencesRoute,
  DashboardResumesIndexRoute: DashboardResumesIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface BuilderResumeIdRouteRouteChildren {
  BuilderResumeIdIndexRoute: typeof BuilderResumeIdIndexRoute;
}

const BuilderResumeIdRouteRouteChildren: BuilderResumeIdRouteRouteChildren = {
  BuilderResumeIdIndexRoute: BuilderResumeIdIndexRoute,
};

const BuilderResumeIdRouteRouteWithChildren =
  BuilderResumeIdRouteRoute._addFileChildren(BuilderResumeIdRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRouteRoute: AgentRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  BuilderResumeIdRouteRoute: BuilderResumeIdRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
